version: '3.7'

services:
  traffic-watcher:
    build:
      context: .
      args:
        BASE_PATH: /traffic
    container_name: traffic-watcher
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - vnstat-data:/var/lib/vnstat
    cap_add:
      - NET_ADMIN

volumes:
  vnstat-data:
